name: PyPi Package upgrade

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unittest
      run: |
        if ! python -m unittest discover tests; then
          exit 1
        fi

    - name: Build package
      run: |
        pip install build twine
        python -m build
        twine check --strict dist/*

    - name: Install toml-cli
      run: |
        curl -O -L https://github.com/ajdavis/toml-cli/releases/download/v0.10.0/toml-cli_0.10.0_linux_amd64.tar.gz
        tar -xzvf toml-cli_0.10.0_linux_amd64.tar.gz
        sudo mv toml-cli /usr/local/bin/toml-cli
        rm toml-cli_0.10.0_linux_amd64.tar.gz
    

    - name: Automate Git Tagging
      run: |
        version=$(toml get pyproject.toml package.version --raw)
        git tag -a "v$version" -m "Release v$version"
        git push origin "v$version"
