name: PyPi Package upgrade

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unittest
      run: |
        if ! python -m unittest discover tests; then
          exit 1
        fi

    - name: Build package
      run: |
        python -m build

    - name: Extract version
      id: extract_version
      run: |
        echo "::set-output name=version::$(python -c "import toml; print(toml.load(open('pyproject.toml'))['project']['version'])")"

    - name: Check if version is updated
      id: check_version
      run: |
        previous_version=$(git describe --tags --abbrev=0)
        current_version=$(grep -oP '(?<=version = ")[^"]*' pyproject.toml)
        if [ "$previous_version" == "$current_version" ]; then
          echo "Error: Version number not updated!"
          exit 1
        fi

    - name: Create GitHub release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ steps.extract_version.outputs.version }}
        release_name: Release ${{ steps.extract_version.outputs.version }}
        files: dist/*